// Build the static client bundle: wrap src/client.js in the DSH client module
// registration format so the host client-modules service can serve it into
// window.__DSH_BOOT__ at runtime (no web-app rebuild needed — the bundle is
// scanned from the live loader entry and served under /plugins).
//
// The wrapper mirrors what tsdown emits for in-repo client packages
// (packages/client/tsdown.client.ts): a CJS factory registered through
// window.__ModuleLoader__.load({ id, factory }), where `require` resolves the
// module table (only 'react' here) and `module.exports` is the plugin.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(import.meta.url))
const body = readFileSync(join(root, 'src', 'client.js'), 'utf8')

const out = [
  '// Generated by build.mjs from src/client.js — do not edit directly.',
  'window.__ModuleLoader__.load({ id: "dsh-ark-usage-widget", factory: (require) => {',
  'var module = { exports: {} };',
  'var exports = module.exports;',
  body,
  'return module.exports;',
  '} });',
  '',
].join('\n')

mkdirSync(join(root, 'lib'), { recursive: true })
writeFileSync(join(root, 'lib', 'client.js'), out)
console.log('wrote lib/client.js (%d bytes)', Buffer.byteLength(out))
